module.exports = {
    'Sunday': 0,
    'sunday': 0,
    'Sundays': 0,
    'sundays': 0,
    'Sun': 0,
    'sun': 0,
    '0': 0,

    'Monday': 1,
    'monday': 1,
    'Mondays': 1,
    'mondays': 1,
    'Mon': 1,
    'mon': 1,
    'M': 1,
    'm': 1,
    '1': 1,

    'Tuesday': 2,
    'tuesday': 2,
    'Tuesdays': 2,
    'tuesdays': 2,
    'Tues': 2,
    'tues': 2,
    'Tue': 2,
    'tue': 2,
    'T': 2,
    't': 2,
    '2': 2,

    'Wednesday': 3,
    'wednesday': 3,
    'Wednesdays': 3,
    'wednesdays': 3,
    'Wed': 3,
    'wed': 3,
    'W': 3,
    'w': 3,
    '3': 3,

    'Thursday': 4,
    'thursday': 4,
    'Thursdays': 4,
    'thursdays': 4,
    'Thurs': 4,
    'thurs': 4,
    'Thur': 4,
    'thur': 4,
    'TH': 4,
    'Th': 4,
    'th': 4,
    '4': 4,

    'Friday': 5,
    'friday': 5,
    'Fridays': 5,
    'fridays': 5,
    'Fri': 5,
    'fri': 5,
    'F': 5,
    'f': 5,
    '5': 5,

    'Saturday': 6,
    'saturday': 6,
    'Saturdays': 6,
    'saturdays': 6,
    'Sat': 6,
    'sat': 6,
    '6': 6,
}